GET http://localhost:7007/api/auth/demo
###
POST http://localhost:7007/api/auth/register

{
    "username": "admin",
    "password": "test123"
}
###
POST http://localhost:7007/api/auth/login

{
    "username": "admin",
    "password": "admin123"
}
###
GET http://localhost:7007/api/protected/user_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTcyODYzMTkwOSwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.P7-Rox7KPxj406-6unwDGh2xT5RSXMVRvibgk8f9MdY
###
GET http://localhost:7007/api/protected/admin_demo
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJUaG9tYXMgSGFydG1hbm4iLCJzdWIiOiJhZG1pbiIsImV4cCI6MTcyODYzMTkwOSwicm9sZXMiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4ifQ.P7-Rox7KPxj406-6unwDGh2xT5RSXMVRvibgk8f9MdY
###
GET http://localhost:7007/api/routes